# Generated by Django 4.2.1 on 2023-09-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('fundamentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('location', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=200)),
                ('contribution', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('organizers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fundamentals.club')),
                ('present', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Presents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=False)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField(default=False)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile')),
            ],
        ),
    ]
